// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84zSmUVYjeYk8k4XQLK41xiY9IYFYHfE',
    appId: '1:553524758441:web:564d1bd12d1c4486d3e6b8',
    messagingSenderId: '553524758441',
    projectId: 'rejoice-8157a',
    authDomain: 'rejoice-8157a.firebaseapp.com',
    storageBucket: 'rejoice-8157a.appspot.com',
    measurementId: 'G-QKGBV5W8L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkkrEcsmn91tezViJf_uwk684Rfoir36A',
    appId: '1:553524758441:android:3031c2f71d8747f6d3e6b8',
    messagingSenderId: '553524758441',
    projectId: 'rejoice-8157a',
    storageBucket: 'rejoice-8157a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlQLGu3Zwl68fS2uiufh2rpA7wT8CfYWI',
    appId: '1:553524758441:ios:a31e5adf26d75002d3e6b8',
    messagingSenderId: '553524758441',
    projectId: 'rejoice-8157a',
    storageBucket: 'rejoice-8157a.appspot.com',
    iosClientId: '553524758441-n91dnnbesl5u74dhihj8ik9t8nflfvd2.apps.googleusercontent.com',
    iosBundleId: 'com.sreshtgeeth.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlQLGu3Zwl68fS2uiufh2rpA7wT8CfYWI',
    appId: '1:553524758441:ios:a31e5adf26d75002d3e6b8',
    messagingSenderId: '553524758441',
    projectId: 'rejoice-8157a',
    storageBucket: 'rejoice-8157a.appspot.com',
    iosClientId: '553524758441-n91dnnbesl5u74dhihj8ik9t8nflfvd2.apps.googleusercontent.com',
    iosBundleId: 'com.sreshtgeeth.app',
  );
}
